-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 11:02:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controllerwebdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `controllerwebdb` ;

-- -----------------------------------------------------
-- Schema controllerwebdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controllerwebdb` DEFAULT CHARACTER SET utf8 ;
USE `controllerwebdb` ;

-- -----------------------------------------------------
-- Table `controllerwebdb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controllerwebdb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `controllerwebdb`.`usuario` (
  `idusuario` VARCHAR(500) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `usuariobloqueado` INT NOT NULL COMMENT '1-Bloqueado, 0-Disponible',
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controllerwebdb`.`electrodomestico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controllerwebdb`.`electrodomestico` ;

CREATE TABLE IF NOT EXISTS `controllerwebdb`.`electrodomestico` (
  `idelectrodomestico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(500) NOT NULL,
  `ubicacion` VARCHAR(500) NOT NULL,
  `estado` TINYINT NOT NULL,
  `usuario_idusuario` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idelectrodomestico`),
  INDEX `fk_electrodomestico_usuario_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_electrodomestico_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `controllerwebdb`.`usuario` (`idusuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controllerwebdb`.`gestordeuso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controllerwebdb`.`gestordeuso` ;

CREATE TABLE IF NOT EXISTS `controllerwebdb`.`gestordeuso` (
  `fkelectrodomestico` INT NOT NULL,
  `horadeencendido` TIME NOT NULL,
  `fechadeencendido` DATE NOT NULL,
  `horadeapagado` TIME NOT NULL,
  INDEX `fk_gestordeuso_electrodomestico1_idx` (`fkelectrodomestico` ASC),
  CONSTRAINT `fk_gestordeuso_electrodomestico1`
    FOREIGN KEY (`fkelectrodomestico`)
    REFERENCES `controllerwebdb`.`electrodomestico` (`idelectrodomestico`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controllerwebdb`.`registrodeusuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controllerwebdb`.`registrodeusuario` ;

CREATE TABLE IF NOT EXISTS `controllerwebdb`.`registrodeusuario` (
  `usuario_idusuario` VARCHAR(500) NOT NULL,
  `horadeentrada` TIME NOT NULL,
  `fechadeentrada` DATE NOT NULL,
  INDEX `fk_registrodeusuario_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_registrodeusuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `controllerwebdb`.`usuario` (`idusuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
